name: WeWork Robot

# Controls when the workflow will run
on:
  issues:
    types: [closed, assigned, opened]
  schedule:
    - cron: '30 8 * * *'
  issue_comment:
    types: [created]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  robot:
    uses: matrixorigin/CI/.github/workflows/robot.yaml@main
    secrets:
      TOKEN_ACTION: ${{ secrets.TOKEN_ACTION}}
      WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK}}
      DOCU_GROUP_HOOK: ${{ secrets.DOCU_GROUP_HOOK}}
